version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: airflow
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - airflow-net

volumes:
  mongo_data:

networks:
  airflow-net:
    driver: bridge
